# Generated by Django 4.0 on 2022-02-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to='portfolio'),
        ),
    ]
