# Generated by Django 4.0.1 on 2022-02-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_alter_portfolio_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='created_at',
        ),
        migrations.AddField(
            model_name='application',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
