# Generated by Django 4.0 on 2022-02-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[(None, '선택'), ('기획/디자인', '기획/디자인'), ('프론트엔드', '프론트엔드'), ('백엔드', '백엔드')], default='선택', max_length=10),
        ),
    ]
